### ISSUE TITLE
Disable scrolling on home page

### ISSUE THREAD

**Issue by jogendra** [NJACKWinterOfCode/HealthLedger#1]
**Actual Behaviour**

The homepage is little scrollable

**Expected Behaviour**

It should cover screen only, and should not be scrollable.

**Screenshots of the issue**

N/A

**Would you like to work on the issue?**

Anyone can claim the issue

**Comment by Vaibhavraj10** [comment]
Can I claim this issue?

**Comment by jogendra** [comment]
@Vaibhavraj10 Yes, sure

**Comment by Vaibhavraj10** [comment]
Thanks. I will soon send the PR.

**Comment by shreeshjha** [comment]
Can I claim this issue
