### ISSUE TITLE
Add Login and Signup user interface

### ISSUE THREAD

**Issue by jogendra** [NJACKWinterOfCode/HealthLedger#3]
**Expected Behaviour**
Add Login and Signup user interface to the homepage

**Would you like to work on the issue?**

Anyone can claim the issue

**Comment by sudipt1999** [comment]
@jogendra  you only need a UI or a functionality in application ! Kindly explain please !

**Comment by jogendra** [comment]
@sudipt1999 As the issue title says, this issue requires UI but you can add functionality after implementing UI.

**Comment by sudipt1999** [comment]
I am not sure if I will be able to add a functionality because I haven't worked a lot with backend , But I will give it a try !

**Comment by thebishaldeb** [comment]
Can I try this?
